# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  schedule:
    - cron: 00 19 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: update the rules
        run:
          cd SmartDNS/
          ./updateRules.sh

      - name: commit
          git config --global user.email ${{ secrets.mail }}
          git config --global user.name ${{ secrets.username }}
          git add .
          tIme=$(date "+%Y-%m-%d %H:%M:%S")
          git commit -m "Updated ${tIme}" -a


      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.token }}
